---
- name: "Packages block"
  block:
    - name: "Remove packages"
      community.general.pacman:
        name: "{{ item }}"
        state: absent
      with_items:
        - "{{ packages_remove }}"

    - name: "Include Config Management Task"
      community.general.pacman:
        name: "{{ item }}"
        state: present
      with_items:
        - libvirt
        - bridge-utils
        - dnsmasq
        - dmidecode
        - virt-manager

    - name: "Systemctl services"
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: yes
      with_items:
        - libvirtd
