---
- name: Include vars
  include_vars:
    dir: ../vars/
    files_matching:
      - archlinux.yaml
      - sectigo.yaml

- name: "Run the equivalent of 'pacman -Sy' as a separate step"
  community.general.pacman:
    update_cache: true

- name: "Packages block"
  block:
    # START BLOCK PACKAGES
    - name: "Install Needed and Extra packages"
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - axel
        - base-devel
        - curl
        - cmake
        - findutils
        - gawk
        - gettext
        - git
        - gnupg
        - hashcat
        - iftop
        - ipcalc
        - linux-firmware
        - lsof
        - make
        - meson
        - mlocate
        - nfs-utils
        - nmap
        - ntp
        - openssh
        - openssl
        - pigz
        - pre-commit
        - procps-ng
        - python-pip
        - rsync
        - sudo
        - sshpass
        - sysstat
        - tar
        - tcpdump
        - traceroute
        - unzip
        - wget
        - whois
        - "{{ extra_packages }}"

    - name: "Install Gui"
      community.general.pacman:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ packages_gui }}"
      when: packages_gui_install == true

    - name: "Systemctl services"
      ansible.builtin.systemd:
        name: "{{ display_manager }}"
        enabled: true
      when: display_manager is defined
      # END BLOCK PACKAGES

- name: "Systemctl services"
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  with_items:
    - sshd
    - bluetooth
