---
# playbook to clone oh-my-zsh
- name: "Install oh-my-zsh"
  hosts: all
  tags: ohmy
  remote_user: "{{ users[0].name |default('root')}}"

  tasks:
    - name: "oh-my-zsh config"
      block:
        - name: "Install dependency packages"
          ansible.builtin.package:
            name: "{{ item }}"
            state: present
          loop:
            - git
            - wget
            - zsh

        - name: Check if .zshrc exists
          ansible.builtin.stat:
            path: ~/.zshrc
          register: stat_zshrc

        - name: "Check if .oh-my-zsh folder exist"
          ansible.builtin.stat:
            path: ~/.config/oh-my-zsh
          register: stat_oh_my_zsh

        - name: "Clone oh-my-zsh"
          ansible.builtin.git:
            repo: "https://github.com/ohmyzsh/ohmyzsh.git"
            dest: "~/.config/oh-my-zsh"
          when: not stat_oh_my_zsh.stat.exists

        - name: Creating new ~/.zshrc
          ansible.builtin.copy:
            src: "~/.oh-my-zsh/templates/zshrc.zsh-template"
            dest: "~/.zshrc"
          when: not stat_zshrc.stat.exists

        - name: "Clone oh-my-zsh plugins"
          ansible.builtin.git:
            repo: "{{ item.repo }}"
            dest: "~/.oh-my-zsh/plugins/{{ item.dest }}"
          with_items:
            - "{{ zsh_plugins }}"
          when: zsh_clone_plugin == true

      when: install_oh_my_zsh == true
