---
user_name: ""
user_comments: ""
user_shell: "/usr/bin/zsh"
user_groups: ["users"]
user_keys: "files/public_keys/id_rsa.pub"

docker_user: "{{ user_name }}"
workstation_user: "{{ user_name }}"

# variables for oh-my-zsh
install_oh_my_zsh: true
zsh_clone_plugin: true
zsh_plugins:
  - name: "Syntax-Highlighting"
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "zsh-syntax-highlighting"
  - name: "Completions"
    repo: "https://github.com/zsh-users/zsh-completions.git"
    dest: "zsh-completions"
  - name: "Autosuggestions"
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "zsh-autosuggestions"

packages_gui: true
display_manager: gdm
packages_gui:
  - xorg
  - gnome
  - gnome-extra
  - gdm

extra_packages:
  - alacritty
  - filezilla
  - docker
  - docker-compose
  - chezmoi
  - thunderbird
  - pwgen
  - aws-cli
  - keychain
  - btop
  - tmux
  - neovim
  - zsh
  - bat

config_management_tools_install: true
packages_config_management:
  - terraform
  - kubectl
  - kubectx
  - kustomize
  - helm
  - sops
  - jq
  - minikube
  - fluxctl
  - packer
  - age
  - vagrant
  - ansible
  - molecule
  - ansible-lint
  - molecule-vagrant
  - yamllint
  - python-psycopg2
  - python-pytest-testinfra
  - python-netaddr
  - python-passlib
  - python-jmespath

yay_packages_install: true
yay_packages:
  - spotify
  - joplin-appimage
  - aur/lens-bin
  - aur/go-task
  - visual-studio-code-bin
  - brave-bin
  - discord

pip_packages:
  - pre-commit

packages_libvirt_install: true
packages_libvirt:
